class LocalizedText {

  static String language = 'English';

  static String get(String key) {
    return texts[language]?[key] ?? 'Key not found';
  }

  static final Map<String, Map<String, String>> texts = {
    'English': {
      'checkDeviceConnection': 'Check Device Connection',
      'openLocaleSettings': 'Open Locale Settings',
      'disableUpdates': 'Disable Updates',
      'enableUpdates': 'Enable Updates',
      'listApps': 'List Apps',
      'saveSelectedApps': 'Save Selected Apps',
      'disableSelected': 'Disable Selected',
      'deleteSelected': 'Delete Selected',
      'languageTab': 'Language',
      'disableUpdatesTab': 'Disable Updates',
      'listAppsTab': 'List Apps',
      'adbOutputTab': 'ADB Output',
      'dashboard': 'Dashboard',
      'applications': 'Applications',
      'settings': 'Setting',
      'phonestatus': 'Phone Status',
      'systemUpdates': 'System Updates',
      'aichat': 'AI Chat',
      'commands': 'Commands',
    },
    'French': {
      'checkDeviceConnection': 'Vérifier la connexion de l\'appareil',
      'openLocaleSettings': 'Ouvrir les paramètres de langue',
      'disableUpdates': 'Désactiver les mises à jour',
      'enableUpdates': 'Activer les mises à jour',
      'listApps': 'Lister les applications',
      'saveSelectedApps': 'Enregistrer les applications sélectionnées',
      'disableSelected': 'Désactiver les sélectionnés',
      'deleteSelected': 'Supprimer les sélectionnés',
      'languageTab': 'Langue',
      'disableUpdatesTab': 'Désactiver les mises à jour',
      'listAppsTab': 'Lister les applications',
      'adbOutputTab': 'Sortie ADB',
      'dashboard': 'Tableau de bord',
      'applications': 'Applications',
      'settings': 'Paramètre',
      'phonestatus': 'État du téléphone',
      'systemUpdates': 'Mises à jour système',
      'aichat': 'Chat IA',
      'commands': 'Commandes',
    },
    'German': {
      'checkDeviceConnection': 'Geräteverbindung prüfen',
      'openLocaleSettings': 'Spracheinstellungen öffnen',
      'disableUpdates': 'Updates deaktivieren',
      'enableUpdates': 'Updates aktivieren',
      'listApps': 'Apps auflisten',
      'saveSelectedApps': 'Ausgewählte Apps speichern',
      'disableSelected': 'Ausgewählte deaktivieren',
      'deleteSelected': 'Ausgewählte löschen',
      'languageTab': 'Sprache',
      'disableUpdatesTab': 'Updates deaktivieren',
      'listAppsTab': 'Apps auflisten',
      'adbOutputTab': 'ADB-Ausgabe',
      'dashboard': 'Armaturenbrett',
      'applications': 'Anwendungen',
      'settings': 'Einstellung',
      'phonestatus': 'Telefonstatus',
      'systemUpdates': 'Systemaktualisierungen',
      'aichat': 'KI-Chat',
      'commands': 'Befehle',
    },
    'Italian': {
      'checkDeviceConnection': 'Controlla connessione dispositivo',
      'openLocaleSettings': 'Apri impostazioni lingua',
      'disableUpdates': 'Disabilita aggiornamenti',
      'enableUpdates': 'Abilita aggiornamenti',
      'listApps': 'Elenca app',
      'saveSelectedApps': 'Salva app selezionate',
      'disableSelected': 'Disabilita selezionati',
      'deleteSelected': 'Elimina selezionati',
      'languageTab': 'Lingua',
      'disableUpdatesTab': 'Disabilita aggiornamenti',
      'listAppsTab': 'Elenca app',
      'adbOutputTab': 'Output ADB',
      'dashboard': 'Cruscotto',
      'applications': 'Applicazioni',
      'settings': 'Impostazione',
      'phonestatus': 'Stato del telefono',
      'systemUpdates': 'Aggiornamenti di sistema',
      'aichat': 'Chat IA',
      'commands': 'Comandi',
    },
  };
}